// Resolucion clase practica 5
def COUNT
pipeline {
    agent any
    parameters {
        string(name: 'palabra', defaultValue: '', description: 'Ingresa la palabra a buscar')
        string(name: 'httpCode', defaultValue: '', description: 'Ingresa el http code a buscar')
    }
    stages {
            stage ('Descargar Logs') {
                steps {
                    // cambiar la url por la que se desee descargar
                    sh 'curl -o /tmp/logfile.log https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs'
                    sh 'ls -lah'
                }   
        }
        stage ('Contar lineas') {
            steps {
                script {
                    COUNT=sh(script: "grep -c 'logstash' /tmp/logfile.log",
                    returnStdout: true).trim()
                    echo "Número de coincidencias encontradas: ${env.COUNT}"
                }
            }
        }
    }
}
